# Generated by Django 3.2.25 on 2024-06-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_category_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(default='A year', max_length=8),
        ),
    ]
