# Generated by Django 3.2.25 on 2024-07-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='contact',
            name='fullname',
            field=models.CharField(default='fullname', max_length=200),
        ),
    ]
