# Generated by Django 3.2.25 on 2024-07-13 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_product_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_review',
            new_name='Review',
        ),
    ]
